version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: expense
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build: .
    ports:
      - '1234:1234'
    environment:
      DATABASE_URL: postgres://postgres:1234@db:5432/expense
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
    depends_on:
      - db
    command: >
      sh -c "pnpm prisma migrate deploy && node dist/main"

volumes:
  postgres_data:
